[UM-20]-created-student-report
archis-academy/ums-backend-feb-subs-1-team pull request #29
Opened 2024-06-21 13:47 UTC by yncrahmet

![konsol](https://github.com/archis-academy/ums-backend-feb-subs-1-team/assets/76149174/22ca3971-2d82-47d1-b0ca-cc2331e83384)

2024-06-21 15:24 UTC, JamshidS requested changes

2024-06-21 15:24 UTC, JamshidS commented on src/main/java/com/archisacadeny/student/StudentRepository.java
> +                do {
you don't need to create a sperate table for storing grades and etc it is already there in Oruj's PR please do take a look together

2024-06-25 16:55 UTC, JamshidS requested changes

2024-06-25 16:55 UTC, JamshidS commented on src/main/java/com/archisacadeny/student/CourseStudentMapper.java
> +    public static void saveToCourseStudentMapper(int studentID,int courseId, double grade){
```suggestion
    public void saveToCourseStudentMapper(int studentID,int courseId, double grade){
```

2024-06-25 16:55 UTC, JamshidS commented on src/main/java/com/archisacadeny/student/StudentRepository.java
> +    public StudentReport generateStudentAchievementReport(int studentId) {
```suggestion
    public Map<String,Object> generateStudentAchievementReport(int studentId) {
```

2024-06-25 16:55 UTC, JamshidS commented on src/main/java/com/archisacadeny/student/StudentRepository.java
> +                double gpa = totalCredits > 0 ? totalWeightedGradePoints / totalCredits : 0.0;
business logic should be inside the service class not repository please do update it accordingly

2024-07-02 10:18 UTC, yncrahmet commented
![çıktı](https://github.com/archis-academy/ums-backend-feb-subs-1-team/assets/76149174/f8df5b85-e93f-4b5e-a509-976ba0abcff4)

2024-07-02 17:11 UTC, JamshidS approved these changes

2024-07-02 17:11 UTC, merged