Course add method
archis-academy/ums-backend-feb-subs-1-team pull request #4
Opened 2024-05-14 14:31 UTC by Orujhimaru

2024-05-14 16:37 UTC, JamshidS requested changes

2024-05-14 16:37 UTC, JamshidS commented on src/main/java/com/archisacadeny/course/CourseRepository.java
> +    public static void addCourse(String course_name,String course_number,String course_instructor,String enrolled_students){
we will discuss how to insert data into a table in todays meeting. this is not the right way to do it.

2024-05-14 17:16 UTC, JamshidS requested changes

2024-05-14 17:16 UTC, JamshidS commented on src/main/java/com/archisacadeny/course/CourseRepository.java
> +                    "course_id SERIAL PRIMARY KEY," + // id SERIAL ?
id
name
number
instructor_id

2024-05-25 09:48 UTC, HKalatas reviewed
Course class ında olan field lar bunlar. SQL bunlara göre değiştirilmeli 

 private long id;
    private String courseName;
    private Instructor instructor;
    private long creditAmount;
    private long totalStudent;
    private List<Student> enrolledStudent;
    private String department;

2024-05-28 17:08 UTC, JamshidS requested changes

2024-05-28 17:08 UTC, JamshidS commented on src/main/java/com/archisacadeny/course/Course.java
> +//    private long id;
please remove all the comments

2024-05-31 15:06 UTC, JamshidS approved these changes

2024-05-31 15:06 UTC, merged