[UM-4]-creating student class
archis-academy/ums-backend-feb-subs-1-team pull request #5
Opened 2024-05-14 17:13 UTC by gorkemiskeceli

2024-05-17 15:15 UTC, JamshidS requested changes

2024-05-17 15:15 UTC, JamshidS commented on src/main/java/com/archisacadeny/student/Student.java
> +    private String enrolledCourse;
```suggestion
    private List<Course> enrolledCourse;
```

2024-05-17 15:15 UTC, JamshidS commented on src/main/java/com/archisacadeny/student/StudentRepository.java
> +    public static void sutendtTable(){
createStudentTable()

2024-05-17 15:15 UTC, JamshidS commented on src/main/java/com/archisacadeny/student/Student.java
> +    private List<String> enrolledCourse;
```suggestion
    private List<Course> enrolledCourse;
```

2024-05-17 15:15 UTC, JamshidS commented on src/main/java/com/archisacadeny/student/StudentRepository.java
> +                    "CREATE TABLE IF NOT EXITS students" +
there is a syntax error you need to add () after table name

2024-05-24 15:28 UTC, JamshidS requested changes

2024-05-24 15:28 UTC, JamshidS commented on src/main/java/com/archisacadeny/student/StudentRepository.java
> +                    "student_number INTEGER,"+
```suggestion
                    "student_number VARCHAR(255),"+
```

2024-05-24 15:28 UTC, JamshidS commented on src/main/java/com/archisacadeny/student/Student.java
> +    private int studentNumber;
```suggestion
    private String studentNumber;
```

2024-05-24 15:28 UTC, JamshidS commented on src/main/java/com/archisacadeny/student/Student.java
> +
and please do share a SS that should show  that your code is working.

2024-05-25 09:40 UTC, HKalatas commented on src/main/java/com/archisacadeny/student/Student.java
> +    private int studentNumber;
Student class ı içinde courseid de olmalı. courseId foreign Key. List<courses>

2024-05-28 17:07 UTC, JamshidS requested changes

2024-05-28 17:07 UTC, JamshidS commented on src/main/java/com/archisacadeny/student/StudentRepository.java
> +                    "enrolled_course VARCHAR(255))";
we don't need enrolled_courses field in table

2024-05-28 17:16 UTC, closed without merging