nehir/[UM-1]-created instructor class
archis-academy/ums-backend-feb-subs-1-team pull request #7
Opened 2024-05-17 12:08 UTC by Nehir0109

2024-05-17 15:12 UTC, JamshidS approved these changes

2024-05-17 15:13 UTC, JamshidS requested changes

2024-05-17 15:13 UTC, JamshidS commented on src/main/java/com/archisacadeny/instructor/Instructor.java
> +    private String instructorName;
```suggestion
    private String name;
```

2024-05-25 09:31 UTC, HKalatas commented on src/main/java/com/archisacadeny/instructor/Instructor.java
> +    private String instructorName;
Instructor class ı içinde courseId de olmalı. Bu field aynı zamand ForeignKey.

2024-05-28 14:11 UTC, Nehir0109 commented
Instructor tablosu oluşturuldu.

<img width="733" alt="Ekran Resmi 2024-05-28 16 27 03" src="https://github.com/archis-academy/ums-backend-feb-subs-1-team/assets/108259897/9cf4c9d4-7541-42de-8bf9-6e6cef6fe01e">

<img width="1216" alt="Ekran Resmi 2024-05-28 16 25 07" src="https://github.com/archis-academy/ums-backend-feb-subs-1-team/assets/108259897/644e54c2-3c3a-4aa9-8f25-72b9c0137f9c">

2024-05-28 17:02 UTC, JamshidS requested changes

2024-05-28 17:02 UTC, JamshidS commented on src/main/java/com/archisacadeny/instructor/Instructor.java
> +    private long id;
```suggestion
    private long instructorId;
```

2024-05-28 17:09 UTC, JamshidS requested changes

2024-05-28 17:09 UTC, JamshidS commented on src/main/java/com/archisacadeny/instructor/InstructorRepository.java
> +                    "instructorId; INTEGER DEFAULT nextval('instructor_id_seq') PRIMARY KEY," +
instructor_id

2024-05-28 17:16 UTC, JamshidS approved these changes

2024-05-28 17:16 UTC, merged